# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyp_PDF <- function(x, mu, sigma, nu, log_p = FALSE) {
    .Call('_bcsnsm_mr_hyp_PDF', PACKAGE = 'bcsnsm.mr', x, mu, sigma, nu, log_p)
}

hyp_CDF <- function(qtl, mu, sigma, nu) {
    .Call('_bcsnsm_mr_hyp_CDF', PACKAGE = 'bcsnsm.mr', qtl, mu, sigma, nu)
}

hyp_QTF <- function(p, nu) {
    .Call('_bcsnsm_mr_hyp_QTF', PACKAGE = 'bcsnsm.mr', p, nu)
}

slash_PDF <- function(x, mu, sigma, nu, log_p = FALSE) {
    .Call('_bcsnsm_mr_slash_PDF', PACKAGE = 'bcsnsm.mr', x, mu, sigma, nu, log_p)
}

slash_CDF <- function(qtl, mu, sigma, nu) {
    .Call('_bcsnsm_mr_slash_CDF', PACKAGE = 'bcsnsm.mr', qtl, mu, sigma, nu)
}

slash_QTF <- function(p, nu) {
    .Call('_bcsnsm_mr_slash_QTF', PACKAGE = 'bcsnsm.mr', p, nu)
}

